---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgB5UrR2lirLnLUnt866+mSpP/3tlJFU9I+G3sjVaOmg9NekJowwuplYOYA+1pwyVbHVPHhz5Br5nogkfIAE6RUlQfdnrpdxJ/1V8FSR033GPpv8FY/C3+Fp/bw6tCrsxzcha69zhxWmTG1ck55K/9i3MapCmuanqBxuon99EZ78s0RxavYkKaaLCwIO5Xpik1pLJ1x0JPicJixHWOL8aIa3IUZTyzk9u5qcD4e/NKfdmpg8OqYZ8d5fgZ7o11XJUSu3Hcg7yrzS7uOqxDmYhhXxsDuckezS4vGydGZRRscaavtVPCWjLeAYKdFsYILBwK2vzSRLSvtQeAxs7qUf912EFCs54wj21l0kAUrcsTQekC7HrdYiNdd2UWugmGRp9OWdN616OCwRk2qZjblSIGTiPpar+/SE5ZR1PUgW3c9lD+T5P8LMg4ci1Srh03eWoZZJvYxMcMnhfFeXhjhxUwzc60kBcq3DNQKgsWC7Ap8GN9cea3zDASaYyuE9ocnGSzfLEUrc+6gOUDBwWzmPT/68r2Io0ulqgn+L8FgQ+zlu7Cxa1lxaqAbAnvwyuj9Zxw9YGk5Cdozi7clOqq7AkRdTt8JbWBjlYvPT2PFknfj/aDSqH/VwkLM/BkIwHKbMevNFubiiaE1ZuotKgSc61ScGKQsVl9fBrPJYYJLvcmQXOp3FO/Fi+f7OLX+Z57MepZcAadtsFcbrHeLOe/0tcL16F5ueoTb3+CPOHNKP99JOGA==
    username: AgCnc+Y2A6CqsJofppBHC0tr95h1jzN02ZFxfPao4Hnu//tefeRGMdoKFnRRhTnzHXc3TWBH2lYJ0WMeMlUPD0hX+XECLPNKQC6cWFY+eUNAxUp+yTeJKtd45xrm1PDMRxrnYlyGXENz2viR56NZWiesYVS5nMOIMmhsuK8SIQOUAtFCjUFOylVtqx/v5lUg1Vi4/ERdZMj7BDaisNWY3X5F2HORf53IZgJ1uEmFHAlwrSZpbglahdHCEd1dQ9s2+5pnqz9he6dAu5FimdeHAPtC9Owe83Y3LJ7h2GVkiadSyZhO7554wlTVj4g5Qi7IITSCqf3djjpf5B5lLKHVf9geshzdAEdHgNJVh9vMbcprCzkSEk0fKhkkYO3gxKavOWJiddgrJk+XbmDMwOF56qjQxBae3nAH0b0YH6kc2D2XjnuiswEDGCM9fFXlaM1SFSu/FA6H1iWNXbKUZIi06EEx/zsO7auXrEnTdR/sIbmIcY6ph9ZKDJ4RbebYRHt+3++0KwoUqT4hohX7ALGeJUzk2wn535pLRmpytXOO8ItSjsRdSUbGQzTEN4xnsFHyAcFqsz806peWrwlYs1fmfdtlyaJf47nd8Fl9jcO6kjVdP8UfsjwCOHU+oMFQru6s0hwmQpZdM1LrRe0Noub26KcYO4EsTioPhzpFnQiRRpp4EszHdu0+RktuubKPt87MclmU3NnnRS7I9A==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak
