---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-client-secrets
  namespace: keycloak
spec:
  encryptedData:
    CONECTA_CLIENT_SECRET: AgA/BGxzUWpOKQKYD/REY1OKKIpZt8bvIev4lZZ+hIarhE8E3revniuBtnU4Z6Phf9s98BoftCKGgQ8e+XdZpdCGwIahXOuzbuw1hThnkGXEDwxIRjGi3CtCRDPP+i3kOf9v1pBLAkKYwxGjw6Pe6DttUNT6jpFdPRsujdoFxl/jngpAEn/GFa5l+PJ5uQiY7VPqBnq6QhPt8v+1dOfM47jot2aADsNremGzR7t7YumqMViUgdDb1kF0lpiaE9LcCa7CkUqbXxvtWptIHEg04j8HNDpvB/NTZfvIwoOvQQ6VPhT0gzyJyEpT1fLV15hl+mnuWCyRJ+1M7pNVYHfjzWLAxJnaOD6M+ZEne5TWyBlkkjjOWVaJmfQBtiywurpkAFjkMHYpO8WlfqMDeVtcMEWcghymLuOJCR1sLZBxxoGYie5ym3m/urr5DBwKXWtLAU2DFJPM42Mej1vDUmmpBdovqBZaH+pYDG+8vt+gOWdrXVhbH3Mvg8XaDuIf/UDbEHCcY2r0GsqEMGxrQ8eti0pbWK6+twQry/+RiZJ1gnL7/nqOWMzQLpW4iXl8vPuT3X9++updjaGfEGGqfO2424EoQkZ+iNkEOCqYBb1gE3p4r/qe/VGUUvwEBl1WudIQlP3KHEKZ3+DR7fu0oWvQG//WkzA4txqpMw6DxeV3pW0eMwTQwO2qaIjVBW9dBHYF6Vm6NmF53xJm5C8ing83cGdsPz9/uCNJrPd96PZmAToNgPZKEPBUYkYiKXZ9hg==
  template:
    metadata:
      name: keycloak-client-secrets
      namespace: keycloak
